#!/bin/zsh

# zsh autoload
autoload -Uz compinit promptinit
compinit
promptinit

# starship
eval "$(starship init zsh)"

# load antigen plugins
source ~/.zsh/antigen.zsh
antigen init "$HOME/.antigenrc"

# load zsh config
typeset -U config_files
config_files=(~/.zsh/*.zsh)

for file in ${config_files}; do
  source "${file}"
done

# make path entries unique
typeset -aU path

# setup homebrew
test -d /home/linuxbrew/.linuxbrew \
    && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
