#!/bin/zsh

# zsh autoload
autoload -Uz compinit promptinit
### only load compinit once a day
for dump in ~/.zcompdump(N.mh+24); do
  compinit
done
compinit -C
###
promptinit

# load zsh config
typeset -U config_files
config_files=(~/.zsh/*.zsh)

for file in ${config_files}; do
  source "${file}"
done

# make path entries unique
typeset -aU path

# setup homebrew
test -d /home/linuxbrew/.linuxbrew \
    && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# load antidote plugins
source "$(brew --prefix)/opt/antidote/share/antidote/antidote.zsh"
antidote load

# starship
eval "$(starship init zsh)"

# optionally load work stuff
if [ -f "$HOME/.custom.zsh" ]; then
  source "$HOME/.custom.zsh"
fi
